[package]
name = "alpha"
version = "0.9.0"
authors = ["nilq <i.am.niels.nielsen@gmail.com>"]
edition = "2018"


[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3


[dependencies]

# async runtime
tokio = { version = "=1.5.0", features = ["macros", "rt-multi-thread", "signal"] }

# utils
rand = "=0.8.3"
regex = "=1.4.5"
time = "=0.2.26"
# uuid generator
nanoid = "=0.1.3"
# mime guesser
tree_magic = "=0.2.3"

# cryptography
# must replace with sha-2 crate
rust-crypto = "0.2.36"

# email
lettre = "=0.9.5"
lettre_email = "=0.9.4"

# web components
hyper = { version = "=0.14.5", features = ["http1", "server", "client", "runtime"] }
urldecode = "=0.1.1"
cookie = { version="=0.15.0", features = ["percent-encode"] }
mime = "=0.3.16"
uriparse = "=0.6.3"

# datetime
chrono = "=0.4.19"
